### ISSUE TITLE
About the installation 

### ISSUE THREAD

**Issue by maramAlghamdi** [flaviostutz/skylight-uas#5]
Hello, 

I would like to use this project on Windows 10 but I am not sure how to install and configure the project.

is there a guide or anything that would help ?

Thank you.

**Comment by flaviostutz** [comment]
Sorry, Mara. We don't have a full guide for it right now, but when I
implemented it I was using Windows, so I think you can have luck doing that.

**Comment by maramAlghamdi** [comment]
I tried to open the project but I could not run the startup.sh file, this error keeps showing up.
![Windows](https://user-images.githubusercontent.com/78991444/122356821-d821cf00-cf5b-11eb-8103-bb6dabf5c78c.png)

**Comment by flaviostutz** [comment]
Have you tried changing the path of the jar file to a known directory in your machine?

**Comment by maramAlghamdi** [comment]
I have downloaded the project file in my "Downloads" folder, but I am not sure since the name of the jar file in the script does not exist, can you please explain to me how to run the project or show me an example.

**Comment by flaviostutz** [comment]
You have to compile it. Compile it using maven from dir /src. It will
compile all submodules and generate various .jar files on your output
folder.
